# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: example.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rexample.proto\x12\x07\x65xample\"\x1c\n\x0cHelloRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\"\x1d\n\nHelloReply\x12\x0f\n\x07message\x18\x01 \x01(\t2\xba\x02\n\x07Greeter\x12\x38\n\x08SayHello\x12\x15.example.HelloRequest\x1a\x13.example.HelloReply\"\x00\x12\x39\n\tSayHello1\x12\x15.example.HelloRequest\x1a\x13.example.HelloReply\"\x00\x12<\n\nSayHelloUS\x12\x15.example.HelloRequest\x1a\x13.example.HelloReply\"\x00\x30\x01\x12<\n\nSayHelloSU\x12\x15.example.HelloRequest\x1a\x13.example.HelloReply\"\x00(\x01\x12>\n\nSayHelloSS\x12\x15.example.HelloRequest\x1a\x13.example.HelloReply\"\x00(\x01\x30\x01\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'example_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _HELLOREQUEST._serialized_start=26
  _HELLOREQUEST._serialized_end=54
  _HELLOREPLY._serialized_start=56
  _HELLOREPLY._serialized_end=85
  _GREETER._serialized_start=88
  _GREETER._serialized_end=402
# @@protoc_insertion_point(module_scope)
