# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import example_pb2 as example__pb2


class GreeterStub(object):
    """The greeting service definition.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SayHello = channel.unary_unary(
                '/example.Greeter/SayHello',
                request_serializer=example__pb2.HelloRequest.SerializeToString,
                response_deserializer=example__pb2.HelloReply.FromString,
                )
        self.SayHello1 = channel.unary_unary(
                '/example.Greeter/SayHello1',
                request_serializer=example__pb2.HelloRequest.SerializeToString,
                response_deserializer=example__pb2.HelloReply.FromString,
                )
        self.SayHelloUS = channel.unary_stream(
                '/example.Greeter/SayHelloUS',
                request_serializer=example__pb2.HelloRequest.SerializeToString,
                response_deserializer=example__pb2.HelloReply.FromString,
                )
        self.SayHelloSU = channel.stream_unary(
                '/example.Greeter/SayHelloSU',
                request_serializer=example__pb2.HelloRequest.SerializeToString,
                response_deserializer=example__pb2.HelloReply.FromString,
                )
        self.SayHelloSS = channel.stream_stream(
                '/example.Greeter/SayHelloSS',
                request_serializer=example__pb2.HelloRequest.SerializeToString,
                response_deserializer=example__pb2.HelloReply.FromString,
                )


class GreeterServicer(object):
    """The greeting service definition.
    """

    def SayHello(self, request, context):
        """Sends a greeting
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SayHello1(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SayHelloUS(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SayHelloSU(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SayHelloSS(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_GreeterServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SayHello': grpc.unary_unary_rpc_method_handler(
                    servicer.SayHello,
                    request_deserializer=example__pb2.HelloRequest.FromString,
                    response_serializer=example__pb2.HelloReply.SerializeToString,
            ),
            'SayHello1': grpc.unary_unary_rpc_method_handler(
                    servicer.SayHello1,
                    request_deserializer=example__pb2.HelloRequest.FromString,
                    response_serializer=example__pb2.HelloReply.SerializeToString,
            ),
            'SayHelloUS': grpc.unary_stream_rpc_method_handler(
                    servicer.SayHelloUS,
                    request_deserializer=example__pb2.HelloRequest.FromString,
                    response_serializer=example__pb2.HelloReply.SerializeToString,
            ),
            'SayHelloSU': grpc.stream_unary_rpc_method_handler(
                    servicer.SayHelloSU,
                    request_deserializer=example__pb2.HelloRequest.FromString,
                    response_serializer=example__pb2.HelloReply.SerializeToString,
            ),
            'SayHelloSS': grpc.stream_stream_rpc_method_handler(
                    servicer.SayHelloSS,
                    request_deserializer=example__pb2.HelloRequest.FromString,
                    response_serializer=example__pb2.HelloReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'example.Greeter', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Greeter(object):
    """The greeting service definition.
    """

    @staticmethod
    def SayHello(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/example.Greeter/SayHello',
            example__pb2.HelloRequest.SerializeToString,
            example__pb2.HelloReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SayHello1(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/example.Greeter/SayHello1',
            example__pb2.HelloRequest.SerializeToString,
            example__pb2.HelloReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SayHelloUS(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/example.Greeter/SayHelloUS',
            example__pb2.HelloRequest.SerializeToString,
            example__pb2.HelloReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SayHelloSU(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(request_iterator, target, '/example.Greeter/SayHelloSU',
            example__pb2.HelloRequest.SerializeToString,
            example__pb2.HelloReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SayHelloSS(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(request_iterator, target, '/example.Greeter/SayHelloSS',
            example__pb2.HelloRequest.SerializeToString,
            example__pb2.HelloReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
